#!/usr/bin/env python3

import argparse
import logging
from mrj3 import Mrj3
import string

parser = argparse.ArgumentParser(description='Control your device via serial port from the command line.')
parser.add_argument('-d', '--device', help='The device you wish to control. ex mrj3', nargs='?', default='mrj3')
parser.add_argument('-p', '--port', help='The serial port your device is connected to. ex: /dev/ttyUSB0', nargs='?', default='/dev/ttyUSB0')
parser.add_argument('-t', '--station', help='The station number to send to the device. ex: 0,1,2,...,9,A,B,...V', nargs='?', default='0')
parser.add_argument('-c', '--command', help='The command to send to the device. ex: 02, slave, ...', required=True)
parser.add_argument('-a', '--action', help='The data no. to send to the device. ex: 70,...', nargs='?', default='.')
parser.add_argument('-i', '--data', help='The data to send to the device.', nargs='?', default="")
parser.add_argument('-e', '--error', help='The error code to send to the device.', nargs='?', default="A")
parser.add_argument('-s', '--serial', help='Extra PySerial config values.')
parser.add_argument("-v", "--verbose", help="verbose output", action="store_const", dest="loglevel", const=logging.INFO, default=logging.WARNING,)
parser.add_argument("--debug",   help="print debug",    action="store_const", dest="loglevel", const=logging.DEBUG,)
args = parser.parse_args()

logging.basicConfig(level=args.loglevel, format='%(created)f %(levelname)s %(message)s')
mrj3 = Mrj3.Mrj3(port=args.port, device_id=args.device)

# command = getattr(mrj3, args.command)
# command(args.station, args.action, args.data, args.error, args.xcommand)
command_args_text = args.command
xcommand_text = ""

# Check if args.command contains only hex digits
if all(c in string.hexdigits for c in command_args_text):
    command_text = 'x'
    xcommand_text = command_args_text
else:
    command_text = command_args_text

command = getattr(mrj3, command_text)
command(args.station, args.action, args.data, args.error, xcommand_text)
